# Different themes have different required and optional fields, look at the documentation for your intended theme to see which you need and/or are available
name: MohamadAli Rezaie
background: https://images.unsplash.com/photo-1544198365-f5d60b6d8190?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80 # An image to use as a background for the site
avatar: https://en.gravatar.com/userimage/89631272/9822ac425f0f9f2b5d4c5900e0881c9b.png?size=200 # The avatar/profile picture of the person's site (put image in images folder and then just the image name here)
email: mrht74@gmail.com
phone: +98 911 458 4737
biography: | # The '|' Used to allow the description to go across multiple lines
  I've graduated from Telecom. Bachelor of Engineering degree, and operation & supply chain management MBA,
  who is interested in high-tech issues, love to learn new things at business concepts, programming, computer networks, and clouds. 
  In favor of freedom, especially free software, and trying to be a geek riding a gravel bike :-)
company: Exa DataScience Lab
address: Narmak, Tehran, Iran
social:
  github: debMan # Your username on github 
  #twitch: idebman # Your username on twitch (everything after https://twitch.tv) i.e. https://twitch.tv/canadiancoding would be canadiancoding
  #youtube: /channel/channel-ID or custom_url # Your custom url (i.e. https://youtube.com/mkbhd would be just mkbhd) or see this guide to find your channel ID: https://support.google.com/youtube/answer/3250431?hl=en
  instagram: idebman # Your username
  twitter: idebman # Your handle (without the @)
  #snapchat: username # Username others use to add you
  linkedin: debman # go to linkedin and go to your profile, your name will be at the end of the url i.e. www.linkedin.com/in/<name>
  facebook: idebman # go to facebook and go to your profile, your ID will be at the end of the url i.e. www.facebook.com/<your id>
  url: https://debman.net # The URL the site will be hosted on (used by resume)
examples: true # If you want to include the example.md files in your final build (good for developing new themes)
theme: cv # The theme you want to use for your site
ua_code: UA-000000-0 # The UA code for google analytics
resume: true # Whether to generate the resume page or not
ignore_exif_data : false # Whether to ignore exif data for gallery images
